spring.application.name=backend

# ===== HEROKU POSTGRES (Variáveis de ambiente) =====
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Porta dinâmica do Heroku
server.port=${PORT:8080}

# ===== CONFIGURAÇÕES ANTIGAS (comentadas) =====
# spring.datasource.url=jdbc:postgresql://localhost:5432/gestaobusiness
# spring.datasource.username=postgres
# spring.datasource.password=root

# spring.datasource.url=jdbc:postgresql://db.oajtirgiiudbmoovdyrv.supabase.co:5432/postgres?user=postgres&password=TvE7JEoQ9OmMHdHD
# spring.datasource.username=postgres
# spring.datasource.password=TvE7JEoQ9OmMHdHD

# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# logging.level.org.springframework.http.converter.json=DEBUG
# logging.level.com.fasterxml.jackson=DEBUG
# logging.level.root=DEBUG